import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  peopleSidebar: [{type: 'autogenerated', dirName: 'people'}],
  researchSidebar: [
    'research/index',
    'research/machine-learning',
    'research/algorithms',
    'research/multiphase',
    'research/random-field',
    'research/projects',
  ],
  publicationsSidebar: [
    {type: 'autogenerated', dirName: 'publications'},
  ],
  resourcesSidebar: [{type: 'autogenerated', dirName: 'resources'}],
  teachingSidebar: [
    'teaching/index',
    {
      type: 'category',
      label: '授课课程',
      link: { type: 'doc', id: 'teaching/courses/index' },
      collapsed: true,
      items: [
        'teaching/courses/engineering-drawing',
        'teaching/courses/linear-algebra',
        'teaching/courses/advanced-computational-mechanics',
        'teaching/courses/discrete-numerical-methods',
      ],
    },
    {
      type: 'category',
      label: '大创项目',
      link: { type: 'doc', id: 'teaching/innovation/index' },
      collapsed: true,
      items: [
        'teaching/innovation/innovation-2023-calcareous-sand',
        'teaching/innovation/innovation-2024-coral-sand-drag',
        'teaching/innovation/innovation-2025-scientific-visualization',
        'teaching/innovation/innovation-2026-underground-evacuation',
      ],
    },
    {
      type: 'category',
      label: '竞赛指导',
      link: { type: 'doc', id: 'teaching/competitions/index' },
      collapsed: true,
      items: [
        'teaching/competitions/apmcm',
        'teaching/competitions/digital-pool',
        'teaching/competitions/sam-cae',
        'teaching/competitions/structural-design',
      ],
    },
  ],
  aboutSidebar: [{type: 'autogenerated', dirName: 'about'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
