import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  peopleSidebar: [{type: 'autogenerated', dirName: 'people'}],
  researchSidebar: [
    'research/index',
    'research/algorithms',
    'research/multiphase',
    'research/random-field',
    'research/machine-learning',
    'research/projects',
  ],
  publicationsSidebar: [{type: 'autogenerated', dirName: 'publications'}],
  resourcesSidebar: [{type: 'autogenerated', dirName: 'resources'}],
  teachingSidebar: [
    'teaching/index',
    'teaching/courses',
    'teaching/engineering-drawing',
    'teaching/linear-algebra',
    'teaching/advanced-computational-mechanics',
    'teaching/discrete-numerical-methods',
    'teaching/innovation',
    'teaching/innovation-2026-underground-evacuation',
    'teaching/innovation-2025-scientific-visualization',
    'teaching/innovation-2024-coral-sand-drag',
    'teaching/innovation-2023-calcareous-sand',
  ],
  aboutSidebar: [{type: 'autogenerated', dirName: 'about'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
